# Use the official Nginx image as a base image
FROM nginx:1.21.6

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy the Nginx configuration from the local machine to the container
COPY nginx.conf /etc/nginx/conf.d/