version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_app
    expose:
      - "5000"
    volumes:
      - ./wiki-data/data.json:/app/wiki-data/data.json

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - app