name: Deploy Wiki
run-name: Updating the wiki
on:
  push:
    branches:
      - main
jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request
        run: curl -X GET hhr-wiki.cheljessen.net:6402/github
